image: sysark/test-isos:latest

# Define the stages
stages:
  - build
  - analyze

build:
  stage: build
  #image: sysark/test-isos:latest
  script:
      - build.sh
  artifacts:
    name: "build_artifacts_$CI_COMMIT_SHORT_SHA"
    paths:
      - artifacts/

analyze:
  stage: analyze
  script:
      - analyze.sh
  artifacts:
    name: "analyze_artifacts_$CI_COMMIT_SHORT_SHA"
    paths:
      - artifacts/
